# Generated by Django 4.1.2 on 2022-11-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_credentials_delete_brokers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokers', models.JSONField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
